version: '3'
services:
  spark-example:
    build: .
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:4.2.9"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    ports:
      - 27017:27017
    stdin_open: true
    tty: true