version: '3'
services:
  spark-example:
    build: .
    environment:
      - MONGODB_URL=mongodb://127.0.0.1:27017/test.myCollection
      - DATA_FILE=report.xlsx
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:4.2.9"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    ports:
      - 27017:27017
    stdin_open: true
    tty: true